### ISSUE TITLE
expose path.repo as an environment variable

### ISSUE THREAD

**Issue by virtuman** [spujadas/elk-docker#102]
Could you please expose "path.repo" as an environment variable. 
This would allow to work with snapshots properly whenever snapshot is on shared volume.

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html

Thank you for consideration.

**Comment by spujadas** [comment]
Instead of making the directory configurable through an environment variable, I'd be more comfortable assigning a fixed directory in the image (`/var/backups` for instance) to be the shared file system repository and having it bind-mounted at runtime as a Docker volume to wherever the shared file system is.
Would that make sense or can you think of an instance where this wouldn't work?

**Comment by exalted** [comment]
Yes, please! 🙏

**Comment by spujadas** [comment]
Hadn't realised that there was demand for this one!
OK with the latest commit, `path.repo` is now defined as `/var/backups` (which is an empty directory belonging to ES in the image).
If you want to give it a spin, it's in `sebp/elk:latest` (build in progress).

**Comment by exalted** [comment]
🤘
