### ISSUE TITLE
How can change default timezone in running contaiter?

### ISSUE THREAD

**Issue by kulevg** [spujadas/elk-docker#111]
Hi.
I cannot change timezone in container from UTC to Europe/Moscow.
My variants in command «docker run» are:
1. add custom timezone file by «-v some_path/timezone:/etc/timezone»
2. add properties «-e "SET_CONTAINER_TIMEZONE=true"  -e "CONTAINER_TIMEZONE=Europe/Moscow"»
3. combination params from 1-2
But after start this container into system has recive

```
# docker exec -it elkx date
Tue Feb  7 14:19:33 UTC 2017
```

Can I change timezone **without** fork image?

**Comment by spujadas** [comment]
Still looking into this.
I think the cleanest way to do this would be for me to update the image to include a new environment variable that can be used to change the timezone, and to change the timezone [as described here](http://serverfault.com/a/683651) (but in the start-up script rather than in the `Dockerfile`).

**Comment by kulevg** [comment]
Hi Sebastien.
In my running container I see this situation: default timezone in inner system are UTC, but logs in elasticsearch/kibana are displayed "on time" into my timezone. Maybe Elastic service appty settings from changed file /etc/timezone or docker_run_props?
So, my problem is resolved and I close this issue.

**Comment by spujadas** [comment]
Interesting and good to know, thanks very much for the update.
