### ISSUE TITLE
Beats plugin needs updating to 2.0.5

### ISSUE THREAD

**Issue by tfgm-bud** [spujadas/elk-docker#12]
Sebastian, 

I know your image targets logstash-forwarder but I thought I'd share this.  I am using your image as a base to test a new config with filebeat.  I assume more and more people with be moving to filebeat so maybe this will help someone else.  I ran into this problem:

  https://discuss.elastic.co/t/issue-with-filebeat-logstash-beats-input-unhandled-exception/33934

which I think is related to using TLS.  I was able to fix it by upgrading the beats plugin as suggested by tudor here:

  https://discuss.elastic.co/t/issue-with-filebeat-logstash-beats-input-unhandled-exception/33934/2

As a workaround for now, in my Docker file, I just added:

    RUN cd /opt/logstash ;\
    ./bin/plugin update logstash-input-beats

-- Bud

**Comment by spujadas** [comment]
Thanks very much for the input, Bud.

I'm planning to gradually phase out everything Lumberjack related (i.e. Logstash forwarder) in favour of Beats, with the next version of the Docker image having "native" support for Beats, so I'll definitely be taking your suggestions on board!

Due to the festive season I haven't got everything I need to work on the image efficiently this week (I need to do more testing on Filebeat + SSL/TLS — wasn't working smoothly last I tried), but I expect to post an updated image next week with the updated Beats plugin.

**Comment by tfgm-bud** [comment]
I suspected that you might move to Filebeat from logstash-forwarder.  Here's the .conf I used for the beat input:

    input {
      beats {
        port => 5044
        ssl => true
        ssl_certificate => "/etc/pki/tls/certs/filebeat.crt"
        ssl_key => "/etc/pki/tls/private/filebeat.key"
      }
    }

Originally, I missed that I needed the "ssl => true".  Note that I generated separate keys for Filebeat.

On the client side, I have the following in my filebeat.yml for the output:
    output:
      logstash:
        enabled: true
        hosts:
          - elk.mydomain.com:5044
        tls:
          certificate_authorities:
            - /etc/pki/tls/certs/filebeat.crt
        timeout: 15

Haven't done a lot of testing but it is working...  -- Bud
