### ISSUE TITLE
Custom container running bug getting no logs from outside.

### ISSUE THREAD

**Issue by Daggerlands** [spujadas/elk-docker#141]
Now that my container is up and running (I can access Kibana). The container is getting no logs. I'm using pfSense to send logs on the port 5140, I exposed it in the Dockerfile and binded it when using the run command, but it's still getting nothing.

**Comment by spujadas** [comment]
If the port is exposed and published, then it sounds like a non-Docker-specific issue with your set-up, and in that case I'd advise that you seek guidance from the Elastic forums over at https://discuss.elastic.co/

Leaving this open for a bit in case it turns out that it actually is an issue with the base image (can't really provide support with custom containers I'm afraid).

**Comment by Daggerlands** [comment]
It is indeed a non Docker issue, I can send logs by hand to the container through the open port.
