### ISSUE TITLE
Any idea how to open a port on udp?

### ISSUE THREAD

**Issue by Daggerlands** [spujadas/elk-docker#144]
I'm having a hard time getting data to my container using udp. I read that I need to use `EXPOSE port/udp` but it's not working.

**Comment by spujadas** [comment]
Please ask for support on generic Docker issues at https://forums.docker.com/
Leaving this open for a while in case it turns out that it's an issue with this image.

**Comment by Daggerlands** [comment]
No one answers anything on that forum, you're the only one providing help so far.

**Comment by spujadas** [comment]
I see, but as I support this image in my spare time, I choose to limit the scope of what I'm willing or able to support (otherwise I'd also be on the Docker or ELK forums helping with generic issues or custom ELK set-ups 😉). I can therefore only redirect you to other support communities for voluntary help.

For instance you can try Stack Overflow, which for now has this to say on your issue: https://stackoverflow.com/questions/27596409/how-do-i-expose-a-udp-port-on-docker, but I expect that you're already exposing and publishing your UDP port, so you may need to provide additional information on your set-up for additional guidance.
