### ISSUE TITLE
still using old logstash pipeline after build

### ISSUE THREAD

**Issue by brianjill** [spujadas/elk-docker#164]
Hi,

I follow the Updating Logstash's configuration from https://elk-docker.readthedocs.io/

here is my Dockerfile
````
FROM sebp/elk

# overwrite existing file
ADD ./conf/logstash/30-output.conf /etc/logstash/conf.d/30-output.conf

# add new file
ADD ./conf/logstash/12-sa_full.conf /etc/logstash/conf.d/12-sa_full.conf
ADD ./conf/logstash/13-tomcat7-stderr.conf /etc/logstash/conf.d/13-tomcat7-stderr.conf
ADD ./conf/logstash/14-tomcat7-stdout.conf /etc/logstash/conf.d/14-tomcat7-stdout.conf
ADD ./conf/logstash/15-sa-log.conf /etc/logstash/conf.d/15-sa-log.conf
ADD ./conf/logstash/29-logstash.conf /etc/logstash/conf.d/29-logstash.conf
````

in the directory where my Dockfile resides, I execute 
````
docker build .
docker-compose up
````
but the .conf is not updated. it is still using the old .conf

please help

**Comment by brianjill** [comment]
i have updated the 12-sa_full.conf file with new indices. but when i harvest new log file from filebeat it is still using the old indeces its not taking the new indices from my update 12-sa_full.conf

**Comment by spujadas** [comment]
If you're literally using these two commands:

	docker build .
	docker-compose up

then you're building one image (from your `Dockerfile`) and starting a container from another image (from your `docker-compose.yml` file – if it's the default one from the GitHub repo, then you're using the sebp/elk image), hence your files not being taken into account. If that's the case, then use `docker-compose build` instead of `docker build`.

Let me know if that was the issue. If it wasn't, could you `docker exec` into the image to check if your configuration files are in `/etc/logstash/conf.d/`.

**Comment by brianjill** [comment]
thanks a lot it worked
