### ISSUE TITLE
Cannot get post-hooks to run

### ISSUE THREAD

**Issue by Petecass** [spujadas/elk-docker#167]
Hi I've been trying to add some custom scripts to this image using `elk-pre-hooks.sh` and `elk-post-hooks.sh`. I have managed to get the `pre-hooks` to run but cannot get the `post-hooks` to run.
The relevant line in my dockerfile: 
```
  FROM sebp/elkx
  ADD ./elk-pre-hooks.sh /usr/local/bin/elk-pre-hooks.sh
  RUN chmod +x /usr/local/bin/elk-pre-hooks.sh

  ADD ./elk-post-hooks.sh /usr/local/bin/elk-post-hooks.sh
  RUN chmod +x /usr/local/bin/elk-post-hooks.sh
```
If you could offer any advice it would be most appreciated. Thanks

**Comment by spujadas** [comment]
Looks good to me.

Could you post the complete output from the start-up sequence?

It could also be due to the _sebp/elkx_ image not being built on top of the version of the _sebp/elk_ image that implements the post-hook feature; could you check in the container if `/usr/local/bin/start.sh` has these lines in it: https://github.com/spujadas/elk-docker/blob/master/start.sh#L193-L220

**Comment by Petecass** [comment]
You're right the `start.sh` script is missing the lines that run the `post-hooks`.  I changed `FROM sebp/elkx` to `FROM sebp/elkx:551` and re built the image, but the `start.sh` file is still missing the required lines.

**Comment by spujadas** [comment]
Oh right I see the issue now: I added post-hooks after `551` and it's not in a tagged version, so it's in `sebp/elk:latest`, but not yet in `sebp/elkx:*` yet.
I'll update `sebp/elk` tonight with the latest versions of ELK, and once they're built (tomorrow) I'll build the `sebp/elkx` images on top of them, which will solve this issue.

**Comment by spujadas** [comment]
OK `sebp/elkx:552` is ready (the later versions up to `561` are being built) if you want to give it a shot.
