### ISSUE TITLE
Support for ELK 6.0

### ISSUE THREAD

**Issue by yannouchou** [spujadas/elk-docker#172]
Hello!
We're starting to evaluate ELK 6 (for, among other things, its support of CSV format for reporting).
Any plans to publish images with the 6.0 stack (now in beta2)?
Security seems to be working a little differently (default passwords don't seem to work any more) so there might be a little more setup needed at least for X-Pack...

Thanks!

**Comment by spujadas** [comment]
Hi!
Yes, the 6.0 stack is most definitely on my to-do list, but I haven't yet had time to try out the beta releases to start reworking the image.
Hope I get the chance this weekend, and will see how it goes from there.

**Comment by yannouchou** [comment]
Great to hear!
Let me know if I can be of some help.


On Wed, Sep 27, 2017 at 2:39 AM, Sébastien Pujadas <notifications@github.com

**Comment by spujadas** [comment]
Will do, cheers!

**Comment by spujadas** [comment]
Haven't had time to really work on ELKX 6 yet, but I've started preparing for ELK 6: if you want to give `sebp/elk:600-rc1` a shot you're more than welcome.

**Comment by yannouchou** [comment]
Cool!

I'm not sure why yet, but with my setup ES doesn't seem to start up, and I couldn't find logs anywhere (at least not in `/var/log/elasticsearch` where they usually are)...

When I run the image without ES I can start it manually with `gosu elasticsearch /opt/elasticsearch/bin/elasticsearch -Epath.logs=/var/log/elasticsearch -Epath.data=/var/lib/elasticsearch` (no `default.` and no `path.config`) but it seems to pick up its configuration from `/opt/elasticsearch/config` instead of `/etc/elasticsearch`.

Any suggestions?

**Comment by yannouchou** [comment]
Note that a big breaking change in ES seems to be that `elasticsearch.yml` not doesn't allow you duplicate keys in the configuration, you have to provide everything in a single tree, but that's not the issue, I've reworked my config accordingly...

**Comment by spujadas** [comment]
Thanks for your feedback. Nothing in the logs likely means that start-up completely failed for some reason, and the right move is indeed to start ES manually to troubleshoot, just as you did. 
In v6 to start ES from the command line you first need to set `ES_PATH_CONF=/etc/elasticsearch` before you run `gosu ...`. This will pick up the right config path.

**Comment by yannouchou** [comment]
Got it! My elastic configuration still had some `xpack.*` settings. If I remove them everything seems ok!
Still, weird that it wouldn't output any logs for an error like this... Even after a successful startup, my log file is correctly created but empty...

**Comment by yannouchou** [comment]
Hello there!
Have you made any progress on elkx?
It looks like the password management works quite differently, with the removal of the default password...

**Comment by spujadas** [comment]
Hiya!

No, haven't really had much time over the past few weeks tbh.

The way passwords now work does indeed make things a tad more complicated. My plan is to have several possible ways of starting a container from the image:

1. Automatically assign new random passwords to the built-in users (the passwords are displayed on screen so that the user can use them if the container is later restarted, see option 3 below), then start all the services. => Easy and straightforward, but only relevant if the user is willing to have randomly set passwords for the built-in users (which may not be the case in production to have an automatable and replicable environment).

2. Start Elasticsearch using either a predefined or user-defined bootstrap password, then leave Elasticsearch running, enabling the user to set the passwords for the built-in users using X-Pack's REST API. => Production-ready (and safe if a user-defined bootstrap password is used), but requires the image to be restarted after the passwords are changed to start the ELKX services (see option 3 below).

3. Once the passwords have been defined for the built-in users (using method 1 or 2 above), start all the services by passing said passwords through env vars.

So yeah, needs a bit of work to check if the above actually works as intended and then make things run reasonably smoothly!

Will see if I can take some time to work on this this week.

**Comment by spujadas** [comment]
Almost there… not quite as per the plan I initially had in mind, but works.

Needs a little more work to enable Logstash's Elasticsearch output plugin to use dynamically defined credentials when authenticating to Elasticsearch. Will finish and publish in the next few days.

**Comment by yannouchou** [comment]
That's great!
Let me know if I can help.
I met with some Elastic representatives yesterday and had a full demo of
ELK6, looks really good. The final release is apparently planned for end of
this month.

**Comment by spujadas** [comment]
Cool, would definitely welcome early feedback once it's ready!
And thanks for the information on the planned release of version 6.

**Comment by spujadas** [comment]
To keep this clean I'm closing this issue and moving the discussion over to the ELKX repo
