### ISSUE TITLE
Elasticsearch is timing out

### ISSUE THREAD

**Issue by Petecass** [spujadas/elk-docker#193]
We have been running the elk image for some months without any problems. A few days ago Elasticsearch started timing out and now it times out after every start up. Its seems to be spending too much time on garbage collection:
`[2018-02-21T10:40:33,667][INFO ][o.e.m.j.JvmGcMonitorService] [xMw5MQR] [gc][old][132][24] duration [8.8s], collections [1]/[9.3s], total [8.8s]/[2.4m], memory [1.7gb]->[1.7gb]/[1.9gb], all_pools {[young] [262.1mb]->[258.4mb]/[399.4mb]}{[survivor] [0b]->[0b]/[49.8mb]}{[old] [1.5gb]->[1.5gb]/[1.5gb]}`

I have tried adjusting the JVM heap size but this has not made a difference whatsoever. Any advice would be greatly appreciated.

**Comment by spujadas** [comment]
>  it times out after every start up

As in the start-up counter going all the way up to `waiting for Elasticsearch to be up (30/30)` and then aborting?
If so then use the `ES_CONNECT_RETRY` to increase the number of seconds that Elasticsearch has to start up.

Alternatively (and generically), assigning more memory to the container may help.

If none of this works, then there is a fair chance that this issue is not specific to this image, so you might get more informed advice over at https://discuss.elastic.co/.

**Comment by Petecass** [comment]
Thanks for the advice. In the end we believe the problem was that there were just too many indexes for Elasticsearch to handle, as deleting some older indexes seems to have fixed the issue. 

Indeed the issue was not related to this issue.

Thanks Again.
