### ISSUE TITLE
Mounting an external configuration file in elk 568

### ISSUE THREAD

**Issue by marcoreni** [spujadas/elk-docker#198]
After updating to ELK:568 my elasticsearch became unreacheable from the outside.

I was able to work around it by changing the mount point for `elasticsearch.yml`.

*BEFORE*:
`- ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml`
*AFTER*:
`- ./elasticsearch.yml:/opt/elasticsearch/config/elasticsearch.yml`

I think this is a bug, since I didn't introduce any other modification and the docs still mention `/etc/elasticsearch` as the config path.

**Comment by spujadas** [comment]
Should now be fixed (was due to breaking changes in ES `path.*` settings introduced in v6 – see https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_packaging_changes.html –, missed it when updating the image from 5.6.4 to 5.6.8), build is in progress, give it a shot and let me know if it works.

**Comment by marcoreni** [comment]
Issue seems to be fixed now.

Thanks,
Marco
