### ISSUE TITLE
Complete config override via env vars

### ISSUE THREAD

**Issue by barravi** [spujadas/elk-docker#223]
Hi

first of all, let me thank you for your excellent work. 
Your docker image just saved my ass allowing me to quickly run a Kibana image against our ES cluster v5, since the official images have no OSS 5 version and I don't have nor I want to install X-Pack. Please keep up the good work and rest assured I'm gonna start helping on this starting next month.

The one cool feature that I noticed in the official ES images that this image is lacking, is the override of EVERY config variable for ES, Logstash and Kibana via ENV vars.

Turns out it's not even that hard to achieve, the script is right here: https://github.com/elastic/kibana-docker/blob/master/build/kibana/bin/kibana-docker so integrating it in your image wouldn't be all too hard, and it would provide a decent mechanism to completely customize the image when running in containerized environments. Right now my workaround is to modify the config files in my startup script using SED, it works but it's kinda dirty.

Thanks in advance!

**Comment by spujadas** [comment]
Hi, thanks for the kind words, and love your enthusiasm!

The feature you mention looks very interesting, would certainly help with a few configuration headaches. At a cursory glance it can't be dropped into the image as is, but it shouldn't be too complicated to adapt it.
If you want to have a shot at a PR for this then by all means go ahead, otherwise let me know and I'll look into it.
