### ISSUE TITLE
need help use logstash udp event

### ISSUE THREAD

**Issue by wjx0912** [spujadas/elk-docker#245]
**create docker:**
```
docker run -d -p 55601:5601 -p 59200:9200 -p 55044:5044  \
  -p 56666:6666/tcp  -p 57777:7777/udp  --name elk sebp/elk:651
```

**port**
56666 for tcp , 57777 for udp,  send data to the  two port , and logstash receive.

**configure**
root@1dbe61ee7f31:/etc/logstash/conf.d# cat /etc/logstash/conf.d/02-beats-input.conf 
```
input {
  beats {
    port => 5044
  }
  udp {
    port => 7777
    codec => json
  }
}
```

**(1)test filebeat**
```
filebeat -e -c filebeat.yml -d "publish"
echo "some text" >> ~/filebeat_listen.log
```
**the result is ok(kibana logs show normal)**

**(2)test command:**
`echo -n "{\"foo\": \"$RANDOM\"}" | nc -q 0 -u  192.168.1.94 57777`
how to add the log to logstash and kibana?

**Comment by spujadas** [comment]
Works fine on my end with the edits you made (`port => 7777` in Logstash's config file and escaping the quotation marks in the test command):

        # echo "{\"foo\": \"$RANDOM\"}" | nc -u -q 0 0.0.0.0 57777
        ^C

The log entries show up (sometimes after a few repetitions of the above, likely due to UDP dropping messages) in Elasticsearch (_http://<host>:59200/_search?pretty_):

  {
    "took" : 1,
    "timed_out" : false,
    "_shards" : {
      "total" : 6,
      "successful" : 6,
      "skipped" : 0,
      "failed" : 0
    },
    "hits" : {
      "total" : 29,
      "max_score" : 1.0,
      "hits" : [
        {
          "_index" : "%{[@metadata][beat]}-2019.01.03",
          "_type" : "%{[@metadata][type]}",
          "_id" : "VfhqFGgBNH5IjS5hfWkQ",
          "_score" : 1.0,
          "_source" : {
            "host" : "172.17.0.1",
            "@timestamp" : "2019-01-03T15:52:29.605Z",
            "@version" : "1",
            "foo" : "25321"
          }
        },
        ...

and in Kibana (creating a index pattern on `*`):

![image](https://user-images.githubusercontent.com/930566/50648041-74b5a980-0f7a-11e9-8d70-df1941392fbc.png)

**Comment by wjx0912** [comment]
@spujadas 
problem fixed. thank you~
