### ISSUE TITLE
Using logstash with UDP

### ISSUE THREAD

**Issue by MohsenSamiei** [spujadas/elk-docker#254]
Hi, How I using your docker image logstash with UDP ?

**Comment by spujadas** [comment]
Hi, configure Logstash to use UDP (as per e.g. https://www.elastic.co/guide/en/logstash/6.6/plugins-inputs-udp.html) and configure Docker to publish/expose the required UDP port (as per e.g. https://docs.docker.com/config/containers/container-networking/).
See #245 for an example.
Closing as this is a support request rather than an issue with the image. For further guidance, please ask for help on e.g. [Elastic](https://discuss.elastic.co/) and/or [Docker](https://forums.docker.com/) forums.

**Comment by MohsenSamiei** [comment]
Thanks
