### ISSUE TITLE
Error in updated filebeat version to 7.9.2?

### ISSUE THREAD

**Issue by jdfx** [spujadas/elk-docker#336]
https://github.com/spujadas/elk-docker/blob/master/nginx-filebeat/Dockerfile

Problem:
`Service 'filebeat' failed to build: The command '/bin/sh -c filebeat export template --es.version ${FILEBEAT_VERSION} > /etc/filebeat/filebeat.template.json' returned a non-zero code: 1
`
Solution:

`ENV FILEBEAT_VERSION 7.9.2`

(remove the oss-). 

I'm fairly new to ELK so not sure if that was the correct fix but it's working for me now. I can sumbit a PR if it's easier.

**Comment by spujadas** [comment]
Nice catch, cheers!

**Comment by spujadas** [comment]
Upon further investigation I reverted that (https://github.com/spujadas/elk-docker/commit/4afc3a73db6a15b57ccf9e61caa039782f7b28bc).
Turns out that installing Filebeat OSS is fine, so left it as is and just changed the version number in the offending line (https://github.com/spujadas/elk-docker/blob/master/nginx-filebeat/Dockerfile#L56).
