### ISSUE TITLE
Help Installing Marvel 

### ISSUE THREAD

**Issue by kenwdelong** [spujadas/elk-docker#34]
I have added these lines to the very bottom of my Dockerfile in my fork (kenwdelong/elk-docker):

ENV ES_HOME /usr/share/elasticsearch
WORKDIR ${ES_HOME}
RUN bin/plugin install license
RUN bin/plugin install marvel-agent
WORKDIR ${KIBANA_HOME}
RUN bin/kibana plugin --install elasticsearch/marvel/2.3.1

Now Kibana won't start.  It won't start using "service kibana start" or "start.sh".  No error messages are printed anywhere, even after adding -v to start_stop_daemon.  Nothing at all is ever printed to kibana4.log.  I chown'd the marvel directory to kibana:kibana, no effect.

However, if I run $KIBANA_HOME/bin/kibana, it all works fine.

I've done everything I could think of, and googled all over the place, and I'm out of ideas.  I know this isn't strictly an issue with this image, but I was hoping someone watching this board would have an idea for me!

**Comment by spujadas** [comment]
Just a shot in the dark, but building the image with your Dockerfile shows this:

	...
	@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
	@     WARNING: plugin requires additional permissions     @
	@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
	* java.lang.RuntimePermission setFactory
	* javax.net.ssl.SSLPermission setHostnameVerifier
	See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
	for descriptions of what these permissions allow and the associated risks.
	...

Not a Java guru by any means, but a cursory glance at http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html suggests that you may want to somehow play around with permissions. My guess is that the reason for the observed behaviour is that `service kibana start` starts Kibana as the user `kibana` (which probably hasn't got the right permissions) whilst running `$KIBANA_HOME/bin/kibana` runs as `root` (which likely has them).

I could be completely wrong, though, being unfamiliar with Java security permissions :confused:

**Comment by kenwdelong** [comment]
Interesting!  Where did you find those errors?

BTW, Kibana appears to be a Node app.  The plot thickens...

**Comment by spujadas** [comment]
Goodness me!
Hmmm... will try and investigate (`strace`-ing around, probably) when I get the chance (also hoping that knowledgeable people watching this find out what could be going on here!)

**Comment by spujadas** [comment]
OK, found it, you can safely ignore my previous tentative explanation. :smiley: 

It turns out that it's a permission-related issue, and the culprit is `/opt/kibana/optimize/.babelcache.json`, as shown by:

	root@709d790dbe92:/opt/kibana# sudo -u kibana $KIBANA_HOME/bin/kibana
	fs.js:549
	  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
	                 ^

	Error: EACCES: permission denied, open '/opt/kibana/optimize/.babelcache.json'
	    at Error (native)
	    at Object.fs.openSync (fs.js:549:18)
	    at Object.fs.writeFileSync (fs.js:1156:15)
	    at save (/opt/kibana/node_modules/babel-core/lib/api/register/cache.js:35:19)
	    at nextTickCallbackWith0Args (node.js:415:9)
	    at process._tickDomainCallback (node.js:385:13)
	    at Function.Module.runMain (module.js:443:11)
	    at startup (node.js:134:18)
	    at node.js:962:3

Having narrowed it down, there are several ways to go about solving this issue (which is apparently a [somewhat](https://discuss.elastic.co/t/kibana-is-not-running/42842) [known](https://github.com/elastic/kibana/issues/6107) [issue](https://github.com/docker-library/kibana/issues/20)):

- `chown kibana:kibana /opt/kibana/optimize/.babelcache.json` (bare minimum, sufficient for the Marvel plugin)

- `chown -R kibana:kibana /opt/kibana` (just to be safe with Kibana plugins in general)

- `USER kibana` before installing the plugin and `USER root` after (mandatory for the container to be able to run `start.sh`, but easy to forget to add this line in the Dockerfile) — tested and working

- Use `sudo -u kibana ...` to install the plugin, but Dockerfile best practices advise against this (https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#user) and recommend installing and using `gosu` (https://github.com/tianon/gosu) instead of `sudo`.

I'll probably add a word on this in the documentation in the next release of the image, as this kind of situation is bound to happen with other plugins.

**Comment by kenwdelong** [comment]
You are a genius!  Thanks!

I had chown'd the plugins dir, but never thought to go one level higher.

My image is working fine.  But I'm wondering about ES.  Most of the files in /usr/share/elasticsearch are owned by root.  Fortunately, I think ES does all its work elsewhere.  But I'm wondering if we should be doing the same trick of switching to the ES user and then back to root?  I google around a little, but didn't see much advice.  I'll look more in a bit.

**Comment by spujadas** [comment]
Cheers! :smile: 
Good point, definitely also need to look into all of the plugins+permissions stuff for all three of the services and document everything.

**Comment by spujadas** [comment]
Closing following image and documentation update (https://github.com/spujadas/elk-docker/commit/59d86d0627504e8e367162ecbc5024d75216627b): have added `gosu` to the base image to make installing plugins easier.
