### ISSUE TITLE
cannot add login page to kibana

### ISSUE THREAD

**Issue by hikmahgumelar** [spujadas/elk-docker#365]
my dockerfile mount kibana.yml and elasticsearch.yml authentication not working

**Comment by spujadas** [comment]
Sounds like an issue configuring the ELK stack rather than an issue with Docker image itself.
I’d recommend heading over to the Elastic forums at https://discuss.elastic.co/ for assistance with the configuration of the services.
Closing this issue, feel free to reopen if it turns out it’s an issue with image after all
