### ISSUE TITLE
Root Disk is 80% full

### ISSUE THREAD

**Issue by gvenka008c** [spujadas/elk-docker#46]
@spujadas 

```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        20G   15G  4.0G  79% /

I logged into the running container and see the /etc/hosts showing as 79%.

/dev/vda1     20G   15G  4.0G  79% /etc/hosts


5997716	/
3244584	/var
2760688	/var/lib
2484128	/var/lib/docker
2448948	/var/lib/docker/volumes
2340880	/var/lib/docker/volumes/a41835047f86ef6f868e93315dfc2d1fe5760c75e390f754311d8a9e27e0be39
2340876	/var/lib/docker/volumes/a41835047f86ef6f868e93315dfc2d1fe5760c75e390f754311d8a9e27e0be39/_data
2328580	/var/lib/docker/volumes/a41835047f86ef6f868e93315dfc2d1fe5760c75e390f754311d8a9e27e0be39/_data/ibdata1
2304924	/usr
796992	/usr/lib
```

Any thoughts on how to clean up?

**Comment by spujadas** [comment]
That's actually a visual artefact of how Docker works: the root disk shows up as being 80% full because your host's disk is 80%. The size of the container itself can be reported using `docker ps -s`, or from within the running container using e.g. `du -cks /`, and should be less than 1GB (excluding log data).

The `/etc/hosts` file in the container specially created by Docker, based on the host's `/etc/hosts` and bind-mounted into the container. Its original location on the host can be revealed by `docker inspect elk | grep hosts`.

So what `df -h /etc/hosts` is actually telling you is that _(deep breath)_ the disk that Docker created the modified `/etc/hosts` file for the container on, i.e. the host's disk, is 79% full. This should match the figure that you have by running `df -h` directly on your the host.

Hope that clarifies.

**Comment by spujadas** [comment]
@gvenka008c Did that solve/clarify your issue?

**Comment by spujadas** [comment]
Housekeeping: closing this issue. Please feel free to reopen if needed.
