### ISSUE TITLE
logstash is not running on centos 7

### ISSUE THREAD

**Issue by meepor** [spujadas/elk-docker#5]
Thanks for putting this solution together.
logstash version 1.5.2
centos7 (LXC)
-----------------------------------
LS_USER=logstash
LS_GROUP=logstash
LS_HOME=/opt/logstash
LS_HEAP_SIZE="500m"
LS_JAVA_OPTS="-Djava.io.tmpdir=${LS_HOME}"
LS_LOG_DIR=/data/log/logstash
LS_LOG_FILE="${LS_LOG_DIR}/$name.log"
LS_CONF_DIR=/opt/logstash/conf.d
LS_OPEN_FILES=16384
LS_NICE=19
LS_OPTS=""
--------------------------------------------------------------------------

I added logstash-init script on Dockerfile, after build image,try to start it an error.
conf files are in use ,I use zip decompression
By the way, I am using this script supervisor monitoring process.

{
[root@log /]# /usr/local/bin/logstash start
touch: cannot touch '/data/log/logstash/logstash.log': No such file or directory
chown: cannot access '/data/log/logstash/logstash.log': No such file or directory
logstash started.
[root@log /]# /usr/local/bin/logstash: line 57: /data/log/logstash/logstash.stdout: No such file or directory
}

**Comment by spujadas** [comment]
> touch: cannot touch '/data/log/logstash/logstash.log': No such file or directory
> chown: cannot access '/data/log/logstash/logstash.log': No such file or directory
> [root@log /]# /usr/local/bin/logstash: line 57: /data/log/logstash/logstash.stdout: No such file or directory

As you changed the `LS_LOG_DIR` environment variable to `/data/log/logstash`, in your `Dockerfile` you need to create the `/data/log/logstash` directory and make it writable by the `logstash` user (which the Logstash service should run as). You want something like:

    mkdir -p /data/log/logstash
    chown logstash:logstash /data/log/logstash

> [root@log /]# /usr/local/bin/logstash start

I'd recommend using:

- either the `service logstash start` (with the original `logstash-init` file copied to `/etc/init.d/logstash` as in the initial Dockerfile) to make sure that the environment is set up correctly and that the proper arguments are passed to `logstash` (and that Logstash is started as `logstash` rather than `root`);

- or – if you don't want to use an init file and want to start Logstash manually instead – something more along the lines of `logstash agent -f ${LS_CONF_DIR} -l ${LS_LOG_FILE} ${LS_OPTS} > "${LS_LOG_DIR}/$name.stdout" 2> "${LS_LOG_DIR}/$name.err" &` (as in the [init file](https://github.com/spujadas/elk-docker/blob/master/logstash-init#L62-L66), making sure that you've also populated `JAVA_OPTS` and the rest of the environment variables).

Let me know if that works out for you.

Oh, and from the output:

> logstash started.

Seems that Logstash did start and may actually be running :smiley: (despite not being able to write out its logs or its stdout/stderr due to the missing directory).

**Comment by meepor** [comment]
@spujadas 
Thanks for the comprehensive instructions. Much appreciated.

It works like a charm!

[root@log /]# /etc/init.d/logstash status
logstash is running

**Comment by meepor** [comment]
Client logs forwarded to the elk host, is stored on the elk?
If so, you need to make a mount volumes to the host,What do you think?

**Comment by spujadas** [comment]
Glad to hear that you got it working!

As for maintaining the logs across restarts, you might want to take a look at [Making log data persistent](https://github.com/spujadas/elk-docker#persistent-log-data), which explains how to create a Docker data volume in the ELK container.

Other options include:

- bind mounting the `/var/lib/elasticsearch` directory in the container to a directory on the host (e.g. `docker run ... -v /some/dir/on/host:/var/lib/elasticsearch ...`);

- adding a `VOLUME /var/lib/elasticsearch` instruction in the `Dockerfile`.

Hope that helps.
