### ISSUE TITLE
cron won't start causing logrotate to never run

### ISSUE THREAD

**Issue by reallistic** [spujadas/elk-docker#60]
My system was brought down the other day by logstash creating a 20GB log file in `/var/log/logstash/logstash.stdout` in less than 24h.

After some debugging I realized the cron daemon isn't running thus logrotate never runs.

**Comment by spujadas** [comment]
Thanks for reporting this (somewhat embarrassing :confused:) issue.
Unfortunately I have limited access to the Internet for the next couple of weeks so won't be able to address this issue until then. Would heartily welcome a PR (to start cron) if you want to give it a shot, otherwise I'll look into this when I'm back online more permanently.

**Comment by reallistic** [comment]
Here you go: https://github.com/spujadas/elk-docker/pull/61

**Comment by spujadas** [comment]
Fantastic! Thanks very much.
