### ISSUE TITLE
Any plan to add X-Pack support?

### ISSUE THREAD

**Issue by kylozw** [spujadas/elk-docker#93]
As title, is there any plan to add X-Pack support, as the default elasticsearch is unsafe.

**Comment by spujadas** [comment]
Sounds like a good idea, will need to do some testing first (especially in cluster set-ups).

**Comment by spujadas** [comment]
Turns out that adding X-Pack introduces user-unfriendly changes for a development/test kind of set-up (in particular everything needs to be authenticated, which is a quite cumbersome), so I've created a new basic [ELKX image](https://github.com/spujadas/elkx-docker) that builds off of the ELK image and adds X-Pack.

It's a bit rough around the edges (haven't done much testing apart from the very basics, wanted to quickly put it out there), but it's simple enough to get started.
Based on user feedback I'll see how I go about enhancing this image.

**Comment by mjaverto** [comment]
@spujadas using this image myself and need a way to get x-pack support. Do you have any suggestions on what is going on? It'd save me some time on engineering research and I'd be happy to contribute back.

**Comment by spujadas** [comment]
@mjaverto Have you had a look at the [ELKX image](https://github.com/spujadas/elkx-docker)? It's the ELK image you're using with X-Pack added on top. Feedback and contributions are most welcome.

**Comment by mjaverto** [comment]
Wow, no that is great @spujadas. Thanks!
